apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: default
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins-container
    image: jenkins/jenkins:lts
    ports:
      - containerPort: 8080
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
