apiVersion: v1
kind: Service
metadata:
  name: spring-boot-postgres-sample
spec:
  selector:
    app: spring-boot-postgres-sample
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32698
  type: NodePort
